version: "3.3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    restart: always
    environment:
      #- bootstrap.memory_lock=true
      - discovery.type=single-node
      #- ES_JAVA_OPTS=-Xms2g -Xmx2g"
      #- ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic2
    volumes:
      - ./volumes/elasticsearch/certs:/usr/share/elasticsearch/config/certs
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    environment:
      - ELASTICSEARCH_HOST:http://elasticsearch:9200
      #- ELASTICSEARCH_USERNAME=elastic
      #- KIBANA_PASSWORD=$ELASTIC_PASSWORD
    ports: 
    - 5601:5601
    depends_on:
      - elasticsearch
    restart: on-failure
    networks:
      - elastic2
    volumes:
    - ./volumes/kibana/certs:/usr/share/kibana/config/certs
    - ./volumes/kibana/user:/usr/share/kibana/data
networks:
  elastic2: {}

